apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: nhnthpppl-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/nhnthpppl-java-quarkus-gitops